### ISSUE TITLE
[Feature] Edit json object in place

### ISSUE THREAD

**Issue by Tomer-EVM** [cainmagi/dash-json-grid#1]
### Get started

- [X] I have read [Contributing guidelines](https://github.com/cainmagi/dash-json-grid/blob/main/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/cainmagi/dash-json-grid/blob/main/CODE_OF_CONDUCT.md).
- [X] I have confirmed that my issue is not duplicated with an existing issue.

### Problem

Hi there and thanks for a great project.

I'm considering using this library but I haven't been able to figure out if I can edit the JSON values or just display them.
I note that it is possible to do so with https://jsongrid.com/json-formatter which appears to be a related project. 

Thanks for your help!

### Required feature

A keyword argument in DashJsonGrid, say, `editable` of type boolean.

E.g. 
```py 
djg.DashJsonGrid(
    id="my-grid",
    data={
        "b":2,
        "complex":{
            "key1":3,
            "key2":4
        }
    },
    editable=True
)
```

This allows the user to edit a particular cell in the grid, which will fire a dash callback such as
``` py
@app.callback(
    Output("json-store", "data"),
    Input("my-grid", "data")
)
def update_json_store(data):
    return data
```

### Dash JSON Grid Viewer version

0.4.3

**Comment by cainmagi** [comment]
## A quick answer

This package is only designed for displaying the data. It cannot offer an inline editor now.

I cannot implement this requested feature. But I can suggest to alternative options if you need this functionality, see the full response.

## A full response

Dear Tomer,

This project is based on [React-JSON-Grid](https://github.com/RedHeadphone/react-json-grid), which is not maintained by me. Your request is difficult to be implemented from my side because I cannot make fundamental modification unless I make the original React Project forked.

Let me explain why this feature is beyond my reach and the functionality of this project:

1. In React-JSON-Grid, the property `data` does not trigger any event. In other words, there is no method named `onDataChange(...)` that can export the current data if it is changed. That's why `dash-json-grid` can only make a callback change `data` but cannot let a user interaction to fire the `data` callback (however, the modification of `data` from a callback indeed can fire another callback).
2. React-JSON-Grid is not a React wrapper of [JSONGrid](https://jsongrid.com/). I believe that JSONGrid itself is not open source. So, React-JSON-Grid does not completely reimplement each feature of that website. Adding the `editable` functionality needs a lot of side works to do, for example, the modification needs to be validated, and the editor needs to provide different interfaces for different data types (`int`, `str`, `bool`, ...). That would be a significant change. I am not sure whether this proposal will be accepted by the original author.

### My suggestion

Here, I can suggest two options

#### Option 1: Use pure `dash` to implement it.

It is possible to use the following packages with `dash-json-grid`:

* [dash-bootstrap-components](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/modal/): A component set providing a `Modal` component.
* [dash-ace](https://github.com/reasoned-ai/dash-ace): A JSON Editor for dash.

You can let `dbc.Modal` to catch the `selected_path` of `dash-json-grid`. It means that, when user clicks a part of the viewer, it will pop up an "editing" window. In that window, you can add a `dash-ace` editor and confirm/cancel buttons. Clicking on the `confirm` button will trigger a callback that will update the `data` of `dash-json-grid` by using the state `selected_path`. That will allow you to partially update the viewer.

#### Option 2: Submit a feature request to React-JSON-Grid

You can check the following link

https://github.com/RedHeadphone/react-json-grid/issues

to submit a feature request issue to React-JSON-Grid, and ask whether it is possible to add an `editable` feature (making the cells triggering inline editors rather than selected) and an event like 
`onDataChange`/`onEdited` (catching changes from user interactions).

--------

Please let me know which option you prefer. I am not intending to fork React-JSON-Grid now. If you prefer the option 1, I will try to update an example (using `dbc` and `dash-ace`) and close this issue after I implement it. If you prefer the option 2, I will close this issue after you submit the issue to `React-JSON-Grid` (certainly, if you would like, you can also let me to submit that issue).

Thank you!
cainmagi

**Comment by Tomer-EVM** [comment]
Dear cainmagi,

Thank you for that informative response. I can now see how much work would be required for this feature!
I like your option 1 implementation idea, and will work towards that functionality.
An example would certainly improve the docs for this use case.

I will not submit a feature request to React-JSON-Grid at this time - feel free to do so if you choose.

Thanks again,
T

**Comment by cainmagi** [comment]
Thank you! Please give me a few days, I should update this demo by the end of this week.

**Comment by cainmagi** [comment]
Hello, Tomer!

I am glad to tell you that I have finalized the demo of the editor. I have also added a document for it:

https://cainmagi.github.io/dash-json-grid/docs/examples/editor

The new version `v0.5.0` does not have any essential changes except for the new demo. So, you do not need to upgrade your package if you want to try the demo.

If you want to run the demo, please install `dash-bootstrap-components` and `dash-ace` first.

Thank you!

Sincerely,
cainmagi
